SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `announcement_dismissals`;
DROP TABLE IF EXISTS `announcements`;
DROP TABLE IF EXISTS `attendance_sessions`;
DROP TABLE IF EXISTS `class_enrollments`;
DROP TABLE IF EXISTS `class_subjects`;
DROP TABLE IF EXISTS `classes`;
DROP TABLE IF EXISTS `curriculum_activities`;
DROP TABLE IF EXISTS `documents`;
DROP TABLE IF EXISTS `emergency_contacts`;
DROP TABLE IF EXISTS `exam_subjects`;
DROP TABLE IF EXISTS `exams`;
DROP TABLE IF EXISTS `expenses`;
DROP TABLE IF EXISTS `fee_structures`;
DROP TABLE IF EXISTS `grading_scales`;
DROP TABLE IF EXISTS `inquiries`;
DROP TABLE IF EXISTS `invoices`;
DROP TABLE IF EXISTS `locations`;
DROP TABLE IF EXISTS `medical_notes`;
DROP TABLE IF EXISTS `otps`;
DROP TABLE IF EXISTS `parents`;
DROP TABLE IF EXISTS `payments`;
DROP TABLE IF EXISTS `plans`;
DROP TABLE IF EXISTS `push_subscriptions`;
DROP TABLE IF EXISTS `report_cards`;
DROP TABLE IF EXISTS `school_announcement_dismissals`;
DROP TABLE IF EXISTS `school_announcements`;
DROP TABLE IF EXISTS `schools`;
DROP TABLE IF EXISTS `staff`;
DROP TABLE IF EXISTS `staff_attendance`;
DROP TABLE IF EXISTS `staff_class_assignments`;
DROP TABLE IF EXISTS `staff_payroll`;
DROP TABLE IF EXISTS `student_attendance`;
DROP TABLE IF EXISTS `student_marks`;
DROP TABLE IF EXISTS `students`;
DROP TABLE IF EXISTS `subjects`;
DROP TABLE IF EXISTS `subscription_payments`;
DROP TABLE IF EXISTS `subscriptions`;
DROP TABLE IF EXISTS `timetable`;
DROP TABLE IF EXISTS `users`;
DROP TABLE IF EXISTS `waitlist`;
DROP TABLE IF EXISTS `__drizzle_migrations`;

SET FOREIGN_KEY_CHECKS = 1;
