SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE `announcement_dismissals`;
TRUNCATE TABLE `announcements`;
TRUNCATE TABLE `attendance_sessions`;
TRUNCATE TABLE `class_enrollments`;
TRUNCATE TABLE `class_subjects`;
TRUNCATE TABLE `classes`;
TRUNCATE TABLE `curriculum_activities`;
TRUNCATE TABLE `documents`;
TRUNCATE TABLE `emergency_contacts`;
TRUNCATE TABLE `exam_subjects`;
TRUNCATE TABLE `exams`;
TRUNCATE TABLE `expenses`;
TRUNCATE TABLE `fee_structures`;
TRUNCATE TABLE `grading_scales`;
TRUNCATE TABLE `inquiries`;
TRUNCATE TABLE `invoices`;
TRUNCATE TABLE `locations`;
TRUNCATE TABLE `medical_notes`;
TRUNCATE TABLE `otps`;
TRUNCATE TABLE `parents`;
TRUNCATE TABLE `payments`;
TRUNCATE TABLE `plans`;
TRUNCATE TABLE `push_subscriptions`;
TRUNCATE TABLE `report_cards`;
TRUNCATE TABLE `school_announcement_dismissals`;
TRUNCATE TABLE `school_announcements`;
TRUNCATE TABLE `schools`;
TRUNCATE TABLE `staff`;
TRUNCATE TABLE `staff_attendance`;
TRUNCATE TABLE `staff_class_assignments`;
TRUNCATE TABLE `staff_payroll`;
TRUNCATE TABLE `student_attendance`;
TRUNCATE TABLE `student_marks`;
TRUNCATE TABLE `students`;
TRUNCATE TABLE `subjects`;
TRUNCATE TABLE `subscription_payments`;
TRUNCATE TABLE `subscriptions`;
TRUNCATE TABLE `timetable`;
TRUNCATE TABLE `users`;
TRUNCATE TABLE `waitlist`;

SET FOREIGN_KEY_CHECKS = 1;
