/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AcademicsRouteImport } from './routes/academics'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as ClassesRouteImport } from './routes/classes'
import { Route as ConfirmRouteImport } from './routes/confirm'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CurriculumRouteImport } from './routes/curriculum'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ExamsRouteImport } from './routes/exams'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as FeesRouteImport } from './routes/fees'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as InvoicePrintRouteImport } from './routes/invoice-print'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ParentRouteImport } from './routes/parent'
import { Route as PnlRouteImport } from './routes/pnl'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SchoolsRouteImport } from './routes/schools'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as InvoicesGenerateRouteImport } from './routes/invoices.generate'
import { Route as StaffIndexRouteImport } from './routes/staff.index'
import { Route as StaffStaffIdRouteImport } from './routes/staff.$staffId'
import { Route as StudentsIndexRouteImport } from './routes/students.index'
import { Route as StudentsStudentIdRouteImport } from './routes/students.$studentId'
import { Route as SuperAdminAnnouncementsRouteImport } from './routes/super-admin.announcements'
import { Route as SuperAdminPaymentsRouteImport } from './routes/super-admin.payments'
import { Route as SuperAdminPlansRouteImport } from './routes/super-admin.plans'
import { Route as SuperAdminSchoolsRouteImport } from './routes/super-admin.schools'
import { Route as SuperAdminSubscriptionsRouteImport } from './routes/super-admin.subscriptions'
import { Route as TeacherIndexRouteImport } from './routes/teacher.index'
import { Route as TeacherAnnouncementsRouteImport } from './routes/teacher.announcements'
import { Route as TeacherAttendanceRouteImport } from './routes/teacher.attendance'
import { Route as SuperAdminSchoolsSchoolIdRouteImport } from './routes/super-admin.schools.$schoolId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsRoute = AcademicsRouteImport.update({
  id: '/academics',
  path: '/academics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesRoute = ClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmRoute = ConfirmRouteImport.update({
  id: '/confirm',
  path: '/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculumRoute = CurriculumRouteImport.update({
  id: '/curriculum',
  path: '/curriculum',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsRoute = ExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const FeesRoute = FeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicePrintRoute = InvoicePrintRouteImport.update({
  id: '/invoice-print',
  path: '/invoice-print',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentRoute = ParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const PnlRoute = PnlRouteImport.update({
  id: '/pnl',
  path: '/pnl',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolsRoute = SchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesGenerateRoute = InvoicesGenerateRouteImport.update({
  id: '/invoices/generate',
  path: '/invoices/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRoute,
} as any)
const StaffStaffIdRoute = StaffStaffIdRouteImport.update({
  id: '/$staffId',
  path: '/$staffId',
  getParentRoute: () => StaffRoute,
} as any)
const StudentsIndexRoute = StudentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentsRoute,
} as any)
const StudentsStudentIdRoute = StudentsStudentIdRouteImport.update({
  id: '/$studentId',
  path: '/$studentId',
  getParentRoute: () => StudentsRoute,
} as any)
const SuperAdminAnnouncementsRoute = SuperAdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminPaymentsRoute = SuperAdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminPlansRoute = SuperAdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminSchoolsRoute = SuperAdminSchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminSubscriptionsRoute = SuperAdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => SuperAdminRoute,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherAnnouncementsRoute = TeacherAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherAttendanceRoute = TeacherAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => TeacherRoute,
} as any)
const SuperAdminSchoolsSchoolIdRoute =
  SuperAdminSchoolsSchoolIdRouteImport.update({
    id: '/$schoolId',
    path: '/$schoolId',
    getParentRoute: () => SuperAdminSchoolsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academics': typeof AcademicsRoute
  '/admissions': typeof AdmissionsRoute
  '/announcements': typeof AnnouncementsRoute
  '/attendance': typeof AttendanceRoute
  '/classes': typeof ClassesRoute
  '/confirm': typeof ConfirmRoute
  '/contact': typeof ContactRoute
  '/curriculum': typeof CurriculumRoute
  '/dashboard': typeof DashboardRoute
  '/exams': typeof ExamsRoute
  '/expenses': typeof ExpensesRoute
  '/fees': typeof FeesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/invite': typeof InviteRoute
  '/invoice-print': typeof InvoicePrintRoute
  '/locations': typeof LocationsRoute
  '/login': typeof LoginRoute
  '/parent': typeof ParentRoute
  '/pnl': typeof PnlRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/schools': typeof SchoolsRoute
  '/signup': typeof SignupRoute
  '/staff': typeof StaffRouteWithChildren
  '/students': typeof StudentsRouteWithChildren
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/terms-of-service': typeof TermsOfServiceRoute
  '/invoices/generate': typeof InvoicesGenerateRoute
  '/staff/$staffId': typeof StaffStaffIdRoute
  '/students/$studentId': typeof StudentsStudentIdRoute
  '/super-admin/announcements': typeof SuperAdminAnnouncementsRoute
  '/super-admin/payments': typeof SuperAdminPaymentsRoute
  '/super-admin/plans': typeof SuperAdminPlansRoute
  '/super-admin/schools': typeof SuperAdminSchoolsRouteWithChildren
  '/super-admin/subscriptions': typeof SuperAdminSubscriptionsRoute
  '/teacher/announcements': typeof TeacherAnnouncementsRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/staff/': typeof StaffIndexRoute
  '/students/': typeof StudentsIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/super-admin/schools/$schoolId': typeof SuperAdminSchoolsSchoolIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academics': typeof AcademicsRoute
  '/admissions': typeof AdmissionsRoute
  '/announcements': typeof AnnouncementsRoute
  '/attendance': typeof AttendanceRoute
  '/classes': typeof ClassesRoute
  '/confirm': typeof ConfirmRoute
  '/contact': typeof ContactRoute
  '/curriculum': typeof CurriculumRoute
  '/dashboard': typeof DashboardRoute
  '/exams': typeof ExamsRoute
  '/expenses': typeof ExpensesRoute
  '/fees': typeof FeesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/invite': typeof InviteRoute
  '/invoice-print': typeof InvoicePrintRoute
  '/locations': typeof LocationsRoute
  '/login': typeof LoginRoute
  '/parent': typeof ParentRoute
  '/pnl': typeof PnlRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/schools': typeof SchoolsRoute
  '/signup': typeof SignupRoute
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/terms-of-service': typeof TermsOfServiceRoute
  '/invoices/generate': typeof InvoicesGenerateRoute
  '/staff/$staffId': typeof StaffStaffIdRoute
  '/students/$studentId': typeof StudentsStudentIdRoute
  '/super-admin/announcements': typeof SuperAdminAnnouncementsRoute
  '/super-admin/payments': typeof SuperAdminPaymentsRoute
  '/super-admin/plans': typeof SuperAdminPlansRoute
  '/super-admin/schools': typeof SuperAdminSchoolsRouteWithChildren
  '/super-admin/subscriptions': typeof SuperAdminSubscriptionsRoute
  '/teacher/announcements': typeof TeacherAnnouncementsRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/staff': typeof StaffIndexRoute
  '/students': typeof StudentsIndexRoute
  '/teacher': typeof TeacherIndexRoute
  '/super-admin/schools/$schoolId': typeof SuperAdminSchoolsSchoolIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academics': typeof AcademicsRoute
  '/admissions': typeof AdmissionsRoute
  '/announcements': typeof AnnouncementsRoute
  '/attendance': typeof AttendanceRoute
  '/classes': typeof ClassesRoute
  '/confirm': typeof ConfirmRoute
  '/contact': typeof ContactRoute
  '/curriculum': typeof CurriculumRoute
  '/dashboard': typeof DashboardRoute
  '/exams': typeof ExamsRoute
  '/expenses': typeof ExpensesRoute
  '/fees': typeof FeesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/invite': typeof InviteRoute
  '/invoice-print': typeof InvoicePrintRoute
  '/locations': typeof LocationsRoute
  '/login': typeof LoginRoute
  '/parent': typeof ParentRoute
  '/pnl': typeof PnlRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/schools': typeof SchoolsRoute
  '/signup': typeof SignupRoute
  '/staff': typeof StaffRouteWithChildren
  '/students': typeof StudentsRouteWithChildren
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/terms-of-service': typeof TermsOfServiceRoute
  '/invoices/generate': typeof InvoicesGenerateRoute
  '/staff/$staffId': typeof StaffStaffIdRoute
  '/students/$studentId': typeof StudentsStudentIdRoute
  '/super-admin/announcements': typeof SuperAdminAnnouncementsRoute
  '/super-admin/payments': typeof SuperAdminPaymentsRoute
  '/super-admin/plans': typeof SuperAdminPlansRoute
  '/super-admin/schools': typeof SuperAdminSchoolsRouteWithChildren
  '/super-admin/subscriptions': typeof SuperAdminSubscriptionsRoute
  '/teacher/announcements': typeof TeacherAnnouncementsRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/staff/': typeof StaffIndexRoute
  '/students/': typeof StudentsIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/super-admin/schools/$schoolId': typeof SuperAdminSchoolsSchoolIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/academics'
    | '/admissions'
    | '/announcements'
    | '/attendance'
    | '/classes'
    | '/confirm'
    | '/contact'
    | '/curriculum'
    | '/dashboard'
    | '/exams'
    | '/expenses'
    | '/fees'
    | '/forgot-password'
    | '/invite'
    | '/invoice-print'
    | '/locations'
    | '/login'
    | '/parent'
    | '/pnl'
    | '/pricing'
    | '/privacy-policy'
    | '/profile'
    | '/refund-policy'
    | '/reset-password'
    | '/schools'
    | '/signup'
    | '/staff'
    | '/students'
    | '/super-admin'
    | '/teacher'
    | '/terms-of-service'
    | '/invoices/generate'
    | '/staff/$staffId'
    | '/students/$studentId'
    | '/super-admin/announcements'
    | '/super-admin/payments'
    | '/super-admin/plans'
    | '/super-admin/schools'
    | '/super-admin/subscriptions'
    | '/teacher/announcements'
    | '/teacher/attendance'
    | '/staff/'
    | '/students/'
    | '/teacher/'
    | '/super-admin/schools/$schoolId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/academics'
    | '/admissions'
    | '/announcements'
    | '/attendance'
    | '/classes'
    | '/confirm'
    | '/contact'
    | '/curriculum'
    | '/dashboard'
    | '/exams'
    | '/expenses'
    | '/fees'
    | '/forgot-password'
    | '/invite'
    | '/invoice-print'
    | '/locations'
    | '/login'
    | '/parent'
    | '/pnl'
    | '/pricing'
    | '/privacy-policy'
    | '/profile'
    | '/refund-policy'
    | '/reset-password'
    | '/schools'
    | '/signup'
    | '/super-admin'
    | '/terms-of-service'
    | '/invoices/generate'
    | '/staff/$staffId'
    | '/students/$studentId'
    | '/super-admin/announcements'
    | '/super-admin/payments'
    | '/super-admin/plans'
    | '/super-admin/schools'
    | '/super-admin/subscriptions'
    | '/teacher/announcements'
    | '/teacher/attendance'
    | '/staff'
    | '/students'
    | '/teacher'
    | '/super-admin/schools/$schoolId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/academics'
    | '/admissions'
    | '/announcements'
    | '/attendance'
    | '/classes'
    | '/confirm'
    | '/contact'
    | '/curriculum'
    | '/dashboard'
    | '/exams'
    | '/expenses'
    | '/fees'
    | '/forgot-password'
    | '/invite'
    | '/invoice-print'
    | '/locations'
    | '/login'
    | '/parent'
    | '/pnl'
    | '/pricing'
    | '/privacy-policy'
    | '/profile'
    | '/refund-policy'
    | '/reset-password'
    | '/schools'
    | '/signup'
    | '/staff'
    | '/students'
    | '/super-admin'
    | '/teacher'
    | '/terms-of-service'
    | '/invoices/generate'
    | '/staff/$staffId'
    | '/students/$studentId'
    | '/super-admin/announcements'
    | '/super-admin/payments'
    | '/super-admin/plans'
    | '/super-admin/schools'
    | '/super-admin/subscriptions'
    | '/teacher/announcements'
    | '/teacher/attendance'
    | '/staff/'
    | '/students/'
    | '/teacher/'
    | '/super-admin/schools/$schoolId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AcademicsRoute: typeof AcademicsRoute
  AdmissionsRoute: typeof AdmissionsRoute
  AnnouncementsRoute: typeof AnnouncementsRoute
  AttendanceRoute: typeof AttendanceRoute
  ClassesRoute: typeof ClassesRoute
  ConfirmRoute: typeof ConfirmRoute
  ContactRoute: typeof ContactRoute
  CurriculumRoute: typeof CurriculumRoute
  DashboardRoute: typeof DashboardRoute
  ExamsRoute: typeof ExamsRoute
  ExpensesRoute: typeof ExpensesRoute
  FeesRoute: typeof FeesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InviteRoute: typeof InviteRoute
  InvoicePrintRoute: typeof InvoicePrintRoute
  LocationsRoute: typeof LocationsRoute
  LoginRoute: typeof LoginRoute
  ParentRoute: typeof ParentRoute
  PnlRoute: typeof PnlRoute
  PricingRoute: typeof PricingRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ProfileRoute: typeof ProfileRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SchoolsRoute: typeof SchoolsRoute
  SignupRoute: typeof SignupRoute
  StaffRoute: typeof StaffRouteWithChildren
  StudentsRoute: typeof StudentsRouteWithChildren
  SuperAdminRoute: typeof SuperAdminRouteWithChildren
  TeacherRoute: typeof TeacherRouteWithChildren
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  InvoicesGenerateRoute: typeof InvoicesGenerateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics': {
      id: '/academics'
      path: '/academics'
      fullPath: '/academics'
      preLoaderRoute: typeof AcademicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes': {
      id: '/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof ClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm': {
      id: '/confirm'
      path: '/confirm'
      fullPath: '/confirm'
      preLoaderRoute: typeof ConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculum': {
      id: '/curriculum'
      path: '/curriculum'
      fullPath: '/curriculum'
      preLoaderRoute: typeof CurriculumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams': {
      id: '/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof ExamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fees': {
      id: '/fees'
      path: '/fees'
      fullPath: '/fees'
      preLoaderRoute: typeof FeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoice-print': {
      id: '/invoice-print'
      path: '/invoice-print'
      fullPath: '/invoice-print'
      preLoaderRoute: typeof InvoicePrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent': {
      id: '/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pnl': {
      id: '/pnl'
      path: '/pnl'
      fullPath: '/pnl'
      preLoaderRoute: typeof PnlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schools': {
      id: '/schools'
      path: '/schools'
      fullPath: '/schools'
      preLoaderRoute: typeof SchoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/generate': {
      id: '/invoices/generate'
      path: '/invoices/generate'
      fullPath: '/invoices/generate'
      preLoaderRoute: typeof InvoicesGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/$staffId': {
      id: '/staff/$staffId'
      path: '/$staffId'
      fullPath: '/staff/$staffId'
      preLoaderRoute: typeof StaffStaffIdRouteImport
      parentRoute: typeof StaffRoute
    }
    '/students/': {
      id: '/students/'
      path: '/'
      fullPath: '/students/'
      preLoaderRoute: typeof StudentsIndexRouteImport
      parentRoute: typeof StudentsRoute
    }
    '/students/$studentId': {
      id: '/students/$studentId'
      path: '/$studentId'
      fullPath: '/students/$studentId'
      preLoaderRoute: typeof StudentsStudentIdRouteImport
      parentRoute: typeof StudentsRoute
    }
    '/super-admin/announcements': {
      id: '/super-admin/announcements'
      path: '/announcements'
      fullPath: '/super-admin/announcements'
      preLoaderRoute: typeof SuperAdminAnnouncementsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/payments': {
      id: '/super-admin/payments'
      path: '/payments'
      fullPath: '/super-admin/payments'
      preLoaderRoute: typeof SuperAdminPaymentsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/plans': {
      id: '/super-admin/plans'
      path: '/plans'
      fullPath: '/super-admin/plans'
      preLoaderRoute: typeof SuperAdminPlansRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/schools': {
      id: '/super-admin/schools'
      path: '/schools'
      fullPath: '/super-admin/schools'
      preLoaderRoute: typeof SuperAdminSchoolsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/subscriptions': {
      id: '/super-admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/super-admin/subscriptions'
      preLoaderRoute: typeof SuperAdminSubscriptionsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/announcements': {
      id: '/teacher/announcements'
      path: '/announcements'
      fullPath: '/teacher/announcements'
      preLoaderRoute: typeof TeacherAnnouncementsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/attendance': {
      id: '/teacher/attendance'
      path: '/attendance'
      fullPath: '/teacher/attendance'
      preLoaderRoute: typeof TeacherAttendanceRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/super-admin/schools/$schoolId': {
      id: '/super-admin/schools/$schoolId'
      path: '/$schoolId'
      fullPath: '/super-admin/schools/$schoolId'
      preLoaderRoute: typeof SuperAdminSchoolsSchoolIdRouteImport
      parentRoute: typeof SuperAdminSchoolsRoute
    }
  }
}

interface StaffRouteChildren {
  StaffStaffIdRoute: typeof StaffStaffIdRoute
  StaffIndexRoute: typeof StaffIndexRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffStaffIdRoute: StaffStaffIdRoute,
  StaffIndexRoute: StaffIndexRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

interface StudentsRouteChildren {
  StudentsStudentIdRoute: typeof StudentsStudentIdRoute
  StudentsIndexRoute: typeof StudentsIndexRoute
}

const StudentsRouteChildren: StudentsRouteChildren = {
  StudentsStudentIdRoute: StudentsStudentIdRoute,
  StudentsIndexRoute: StudentsIndexRoute,
}

const StudentsRouteWithChildren = StudentsRoute._addFileChildren(
  StudentsRouteChildren,
)

interface SuperAdminSchoolsRouteChildren {
  SuperAdminSchoolsSchoolIdRoute: typeof SuperAdminSchoolsSchoolIdRoute
}

const SuperAdminSchoolsRouteChildren: SuperAdminSchoolsRouteChildren = {
  SuperAdminSchoolsSchoolIdRoute: SuperAdminSchoolsSchoolIdRoute,
}

const SuperAdminSchoolsRouteWithChildren =
  SuperAdminSchoolsRoute._addFileChildren(SuperAdminSchoolsRouteChildren)

interface SuperAdminRouteChildren {
  SuperAdminAnnouncementsRoute: typeof SuperAdminAnnouncementsRoute
  SuperAdminPaymentsRoute: typeof SuperAdminPaymentsRoute
  SuperAdminPlansRoute: typeof SuperAdminPlansRoute
  SuperAdminSchoolsRoute: typeof SuperAdminSchoolsRouteWithChildren
  SuperAdminSubscriptionsRoute: typeof SuperAdminSubscriptionsRoute
}

const SuperAdminRouteChildren: SuperAdminRouteChildren = {
  SuperAdminAnnouncementsRoute: SuperAdminAnnouncementsRoute,
  SuperAdminPaymentsRoute: SuperAdminPaymentsRoute,
  SuperAdminPlansRoute: SuperAdminPlansRoute,
  SuperAdminSchoolsRoute: SuperAdminSchoolsRouteWithChildren,
  SuperAdminSubscriptionsRoute: SuperAdminSubscriptionsRoute,
}

const SuperAdminRouteWithChildren = SuperAdminRoute._addFileChildren(
  SuperAdminRouteChildren,
)

interface TeacherRouteChildren {
  TeacherAnnouncementsRoute: typeof TeacherAnnouncementsRoute
  TeacherAttendanceRoute: typeof TeacherAttendanceRoute
  TeacherIndexRoute: typeof TeacherIndexRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherAnnouncementsRoute: TeacherAnnouncementsRoute,
  TeacherAttendanceRoute: TeacherAttendanceRoute,
  TeacherIndexRoute: TeacherIndexRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AcademicsRoute: AcademicsRoute,
  AdmissionsRoute: AdmissionsRoute,
  AnnouncementsRoute: AnnouncementsRoute,
  AttendanceRoute: AttendanceRoute,
  ClassesRoute: ClassesRoute,
  ConfirmRoute: ConfirmRoute,
  ContactRoute: ContactRoute,
  CurriculumRoute: CurriculumRoute,
  DashboardRoute: DashboardRoute,
  ExamsRoute: ExamsRoute,
  ExpensesRoute: ExpensesRoute,
  FeesRoute: FeesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InviteRoute: InviteRoute,
  InvoicePrintRoute: InvoicePrintRoute,
  LocationsRoute: LocationsRoute,
  LoginRoute: LoginRoute,
  ParentRoute: ParentRoute,
  PnlRoute: PnlRoute,
  PricingRoute: PricingRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ProfileRoute: ProfileRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SchoolsRoute: SchoolsRoute,
  SignupRoute: SignupRoute,
  StaffRoute: StaffRouteWithChildren,
  StudentsRoute: StudentsRouteWithChildren,
  SuperAdminRoute: SuperAdminRouteWithChildren,
  TeacherRoute: TeacherRouteWithChildren,
  TermsOfServiceRoute: TermsOfServiceRoute,
  InvoicesGenerateRoute: InvoicesGenerateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
